# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1536c2c3b925f074b8e4cf13579ddb4561dc82fbe96ec5a2f139134ddeacf1c4567be734162a4539773049c7d4b109c7cf2f9be8eff99fe2673fca95db8efc0d

test:
  secret_key_base: f787dba8a4bffa45c83938c91f4ddd18f582e879826e71181a26657fc7643decb81cdc49f589b7223a8e800664936f5a1848f03ea3348c12c4afbe17699d536d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
